status = [
  # Buildkite: impure builds
  "buildkite/cardano-metadata-submitter",
  # Hydra: build for required jobset
  "ci/hydra:Cardano:cardano-metadata-submitter:required",
]
timeout_sec = 3600
required_approvals = 1
delete_merged_branches = true
block_labels = [ "DO NOT MERGE", "wip" ]
